name: one_d_m
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  provider: ^4.0.4
  image_picker: ^0.6.7+7
  async: ^2.4.0
  firebase_core: ^0.5.3
  firebase_auth: ^0.18.4+1
  cloud_firestore: ^0.14.4
  firebase_storage: ^5.2.0
  path_provider: ^1.6.5
  uuid: ^2.0.4
  cached_network_image: ^2.0.0
  timeago: ^2.0.26
  animations: ^1.0.0+5
  transparent_image: ^1.0.0
  contacts_service: ^0.4.6
  permission_handler: ^5.0.0+hotfix.4
  stripe_payment: ^1.0.7
  cupertino_tabbar: ^1.0.1
  flutter_staggered_grid_view: ^0.3.0
  ink_page_indicator: ^0.1.2
  flutter_svg: ^0.18.0
  cloud_functions: ^0.7.2
  firebase_messaging: ^6.0.15
  share: ^0.6.4+3
  implicitly_animated_reorderable_list: ^0.2.2
  auto_size_text: ^2.1.0
  flutter_offline: ^0.3.0
  sign_in_with_apple: ^2.4.0
  google_sign_in: ^4.5.1
  flutter_signin_button: ^1.0.0
  package_info: ^0.4.1
  firebase_remote_config: ^0.4.3
  url_launcher: ^5.7.10
  shared_preferences: ^0.5.10
  firebase_admob: ^0.10.3
  numberpicker: ^1.2.1
  flutter_xlider: ^3.4.0
  lottie: ^0.7.0+1
  flutter_hooks: ^0.15.0
  number_slide_animation: ^0.1.1
  flutter_local_notifications: ^3.0.2
  rxdart: ^0.25.0
  line_icons: ^0.2.0
  timeline_tile: ^1.0.0
  expandable: ^4.1.4
  charcode: ^1.1.3
  palette_generator: ^0.2.3
  flutter_ffmpeg: ^0.2.10
  video_player: ^1.0.1
  visibility_detector: ^0.1.5
  carousel_slider: ^2.3.1
  animated_stream_list: ^1.1.0

dev_dependencies:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - assets/images/
    - assets/icons/
    - assets/anim/
