name: one_d_m
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.36+126

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^5.0.0
  image_picker: ^0.8.4+1
  async: ^2.4.0

  firebase_core: ^1.6.0
  firebase_auth: ^3.1.1
  cloud_firestore: ^2.5.2
  firebase_storage: ^10.0.3
  firebase_remote_config: ^0.11.0
  cloud_functions: ^3.0.3
  firebase_messaging: ^10.0.7
  # firebase_admob: ^0.11.2
  firebase_dynamic_links: ^2.0.9
  firebase_analytics: ^8.3.2
  google_mobile_ads: ^0.13.4

  path_provider: ^2.0.3
  uuid: ^3.0.4
  cached_network_image: ^3.1.0
  timeago: ^3.1.0
  animations: ^2.0.1
  transparent_image: ^2.0.0
  contacts_service: ^0.6.1
  permission_handler: ^8.1.6
  # stripe_payment: ^1.1.0
  flutter_staggered_grid_view: ^0.4.0
  ink_page_indicator: ^0.2.1
  flutter_svg: ^0.22.0

  auto_size_text: ^3.0.0-nullsafety.0
  flutter_offline: ^2.0.0
  # sign_in_with_apple: ^2.4.0f
  # google_sign_in: ^4.5.1
  expandable: ^5.0.1
  timeline_tile: ^2.0.0
  package_info: ^2.0.2

  url_launcher: ^6.0.5
  shared_preferences: ^2.0.7
  numberpicker: ^2.1.1
  lottie: ^1.1.0
  number_slide_animation: ^0.2.1
  charcode: ^1.1.3
  visibility_detector: ^0.2.0
  should_rebuild: ^1.0.1
  video_player: ^2.2.0
  flutter_cache_manager: ^3.1.2
  chewie: ^1.0.0
  image_cropper: ^1.3.1
  intl: ^0.17.0
  auto_animated: ^3.0.0
  flare_flutter: ^3.0.2
  download_assets: ^2.0.0
  rive: ^0.7.12
  modal_bottom_sheet: ^2.0.0
  styled_text: ^3.0.3
  flutter_blurhash: ^0.6.0
  flutter_material_color_picker: ^1.0.5
  social_share: ^2.1.1
  screenshot: ^1.2.1
  feature_discovery: ^0.14.0
  http: ^0.13.3
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  sliver_tools: ^0.2.5
  flutter_applovin_max: ^2.0.0

#  video_player:
#    git:
#      url: https://github.com/sanekyy/plugins.git
#      ref: caching
#      path: packages/video_player/video_player

dev_dependencies:
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  ios: false
  android: true
  image_path: 'assets/launcher/odm_icon.png'
  adaptive_icon_background: 'assets/launcher/odm_icon_background.png'
  adaptive_icon_foreground: 'assets/launcher/odm_icon_foreground.png'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
